name: Build pandoc and push content to Pages

on:
  push:
    branches: ["master", "wip-pandoc"] # TODO
  pull_request:
    branches: [ "master" ] # TODO REMOVE?

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# TODO should restrict access to only the master branch:
# https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nikeee/setup-pandoc@v1

    - run: node --version
    - run: node scripts/publish.js

    - uses: actions/upload-artifact@v3
      with:
        name: html
        path: build/index.html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
        id: deployment