name: Build pandoc and push content to Pages

on:
  push:
    branches: ["master", "wip-pandoc"] # TODO
  pull_request:
    branches: [ "master" ] # TODO REMOVE?

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nikeee/setup-pandoc@v1
    
    - run: node --version
    - run: echo "# Test" | pandoc -o index.html
    - uses: actions/upload-artifact@v3
      with:
        name: html
        path: index.html